Done task proxy
Glelg/master-programming-task pull request #2
Opened 2020-01-18 16:53 UTC by Glelg

All tests passed (15 assertions in 4 test cases)

2020-01-18 17:09 UTC, igsha requested changes
Сам код правильный, но circle-ci не собирает и не проверяет проект. И надо избавиться от дублирования первой лабораторной.
Сейчас можно несколько лабораторных сдавать в одном пулл-реквесте.

2020-01-18 17:09 UTC, igsha commented on iomanip/include/iomanip.hpp
> +static std::ostream& endm(std::ostream& os)
зачем здесь ещё одна лаба, которая в другом пулл-реквесте?

2020-01-19 06:24 UTC, igsha commented
Сейчас смёржить пулл-реквест не даёт гитхаб, так как есть конфликты: некоторые коммиты в ветке делают то же самое, что уже сделано в мастере. Для пердотвращения кофликтов, нужно:
1. Спуллить свой текущий мастер:

    ```
    git checkout master
    git pull
    ```
1. Переключиться обратно на свою ветку: `git checkout proxy`
1. Интерактивно отрибейзиться от мастера и дропнуть 1 коммит и последний при рибейзе: `git rebase -i master`. Чтобы дропнуть коммит, нужно поставить букву `d` перед ним.
1. Запушить ветку с форсом `git push --force`, так как мы сделали непоследовательное изменение.

2020-01-19 11:02 UTC, igsha commented
@Glelg, а, увидел: всё собирается. Тогда поправьте конфликты.

2020-01-19 12:56 UTC, igsha requested changes
Всё= пока не могу замёржить, надо откатить комментарий

2020-01-19 12:56 UTC, igsha commented on CMakeLists.txt
>  #add_subdirectory(iomanip)
вот эту строчку надо откатить, убрать комментарий. После это коммит сделайте с `--amend`

2020-01-19 13:07 UTC, Glelg commented on CMakeLists.txt
>  #add_subdirectory(iomanip)
при этом надо заново делать коммит iomanip?

2020-01-19 13:09 UTC, igsha commented on CMakeLists.txt
>  #add_subdirectory(iomanip)
нет, не надо: iomanip должен **сам** прилететь из мастера. Судя по всему Вы не делаете первый шаг: свой локальный мастер не спулили `git pull origin master:master`

2020-01-19 13:40 UTC, Glelg commented on CMakeLists.txt
>  #add_subdirectory(iomanip)
Как быть с конфликтом старого и нового CMakeLists?

2020-01-19 13:59 UTC, igsha commented on CMakeLists.txt
>  #add_subdirectory(iomanip)
Руками править. При рибейзе нужно уже руками править конфликты:
```
$ git rebase master
$ git diff
diff --cc CMakeLists.txt
index 94e8f83,b5ed79e..0000000
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@@ -17,7 -17,7 +17,11 @@@ set(BUILD_SHARED_LIBS ON) # need for Bo
  find_package(Boost 1.68 REQUIRED COMPONENTS system)
  
  add_subdirectory(iomanip)
++<<<<<<< HEAD
 +#add_subdirectory(proxy)
++=======
+ add_subdirectory(proxy)
++>>>>>>> Update task iomanip
  #add_subdirectory(iterator)
  #add_subdirectory(variant)
  #add_subdirectory(type_map)
$ # вот тут правим файл: удаляем <<<<HEAD, #add_subdirectory(proxy) и >>> Update task iomanip
$ git add CMakeLists.txt 
$ git rebase --continue 
$ git push --force
```

2020-01-19 14:23 UTC, igsha commented on CMakeLists.txt
> +=======
А это что за `====`?

2020-01-19 14:45 UTC, igsha approved these changes
Наконец-то! Теперь всё правильно отрибейзили.
Зачтено, 8 баллов.

2020-01-19 14:45 UTC, merged